# Evaluation of Synthetic Data Generation Methods for Tabular Health Data

## Models Evaluated

In this study we evaluate both probabilistic and generative synthetic data generation methods on tabular health data,
using implementations from **Synthetic Data Vault (SDV)** and **synthcity** Python libraries.

For each model we also try a differentially private (DP) version and later evaluate both.

### Probabilistic

1. **Gaussian Copulas** - Baseline in general
    - `GaussianCopulaSynthesizer`
    - `DPGCSynthesizer` (DP version)
2. **Bayesian Networks**
    - `BayesianNetworkPlugin`
    - `PrivBayes` (DP version)

### Generative

1. **Generative Adversarial Networks**
    - `CTGAN` - baseline in generative models
    - DP variants: `DP-GAN`, `PATEGAN`, `AdsGAN`
2. **Variational Auto-Encoders**
    - `TVAE`, `RTVAE`
    - DP variants
3. **Normalizing Flows**
4. **Autoregressive / Tree-Based Models**
    - ARF (Adversarial Random Forests)
5. **Diffusion Models** (1)
    - `TabDDPM` (DP)
    - `TableDiffusion` (DP)

## Data

A public clinical dataset **Heart Disease** from **UC Irvine Machine Learning Repository** is used in this study.

In [ ]:
from ucimlrepo import fetch_ucirepo

heart_disease = fetch_ucirepo(id=45)

X = heart_disease.data.features
y = heart_disease.data.targets

X

In [2]:
import pandas as pd

X = pd.read_csv("heart.csv")
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

# Generative Models

## Generative Adversarial Network (GAN)

In this section we use GAN models to generate synthetic datasets from our original data.

### General Idea

There are two components - generator and discriminator. Generator creates a realistic synthetic row of tabular data with random noise applied. Discriminator acts as a binary classifier deciding whether the provided row is real or fake (0-1), taking either real or synthetic row as an input.

`[insert GAN loss function here]`

Discriminator (D) wants to classify correctly real samples (high probability) and fake samples (low probability).

Generator (G) wants to make Discrimator (D) classify fake samples as real.

### GAN on Tabular Data

Conditional Tabular Generative Adversarial Network (CTGAN) can explicitly condition the data generation process on specific categorical variables.

A typical CTGAN training loop:

1. Sample real batch from dataset.
2. Sample noise z.
3. Generator creates synthetic samples G(z).
4. Discriminator trains on:
    - real samples → label 1
    - fake samples → label 0
5. Generator trains to fool the discriminator:
    - update G so D(G(z)) → 1
6. Apply conditional constraints (CTGAN)
7. Repeat until convergence.

In [2]:
from synthcity.plugins import Plugins

Plugins().list()

/workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[KeOps] Warning : CUDA libraries not found or could not be loaded; Switching to CPU only.

[2025-11-23T20:44:40.514295+0000][79342][CRITICAL] Error importing TabularGoggle: No module named 'dgl'
[2025-11-23T20:44:40.518445+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py

['timevae',
 'adsgan',
 'radialgan',
 'survival_nflow',
 'decaf',
 'fflows',
 'ctgan',
 'dpgan',
 'ddpm',
 'uniform_sampler',
 'survival_gan',
 'aim',
 'privbayes',
 'tvae',
 'arf',
 'great',
 'survae',
 'marginal_distributions',
 'image_cgan',
 'image_adsgan',
 'dummy_sampler',
 'bayesian_network',
 'rtvae',
 'nflow',
 'pategan',
 'timegan',
 'survival_ctgan']

Create a train and test data loaders for **synthcity**.

In [3]:
from synthcity.plugins.core.dataloader import GenericDataLoader
loader = GenericDataLoader(
    X,
    target_column="target",
)
train_loader, test_loader = loader.train(), loader.test()

Load the CTGAN plugin class.

In [4]:
plugin_cls = type(Plugins().get("ctgan"))
plugin_cls
# plugin = Plugins().get("ctgan", n_iter = 100)

[2025-11-23T20:45:10.642427+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py

synthcity.plugins.generic.plugin_ctgan.CTGANPlugin

### CTGAN plugin in synthcity

Most parameters of the plugin describe architectures or training loop of Generator (G) and Discriminator (D) neural networks.

#### Generator parameters

- `generator_n_layers_hidden`: how many hidden layers the generator neural network has (excluding input/out). More layers -> more capacity, but slower + risk of overfitting.
- `generator_n_units_hidden`: number of neurons per hidden layer. Controls generator model size.
- `generator_nonlin`: activation function used between layers:
    - `leaky_relu` - default, stable for GANs
    - `relu` - simpler
    - `elu` / `selu` - sometimes help with continuous skewed data
- `generator_dropout`: fraction of neurons randomly dropped during training. Prevents overfitting. Usually 0 for tabular GANs.
- `n_iter`: total number of training iterations (epochs). Higher -> better model (until overfitting), longer training.

#### Discriminator parameters

- `discriminator_n_layers_hidden`: how many hidden layers the discriminator has.
- `discriminator_n_units_hidden`: number of neurons per layer
- `discriminator_nonlin`: activation function for the discriminator.
- `discriminator_dropout`: dropout regularization for the discriminator.
- `discriminator_n_inter`: number of discriminator update steps per cycle.

#### Optimization and training

- `lr`: learning rate for both generator and discriminator
- `weight_decay`: L2 regularization on weights, which prevents exploding weights (and overfitting). Adds penalty to the loss function proportional to the sum of squares of the model's weights.
- `batch_size`: mini-batch size used during training. For a small dataset like in our case (303 rows), values 32-128 work good.
- `random_state`: random seed for reproducibility.
- `clipping_value`: gradient clipping threshold.

#### Preprocessing / encoding

- `encoder_max_clusters`: continuous variables are encoded using mode-specific normalization. This parameter controls the max number of mixture components (clusters) used. More clusters = better modeling of multimodal distributions, slower training.

To automatically tune hyperparameters in `synthcity`, we use hyperparameter optimization (HPO) algorithms such as Tree-structured Parzen estimators (TPE), Bayesian optimization, and genetic programming.

We will use `optuna` HPO library, which implements TPE, to tune hyperparameters.

Display the hyperparameter space.

In [5]:
plugin_cls.hyperparameter_space()

[IntegerDistribution(name='generator_n_layers_hidden', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=None, low=1, high=4, step=1),
 IntegerDistribution(name='generator_n_units_hidden', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=None, low=50, high=150, step=50),
 CategoricalDistribution(name='generator_nonlin', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=elu           0.25
 leaky_relu    0.25
 relu          0.25
 tanh          0.25
 dtype: float64, choices=['elu', 'leaky_relu', 'relu', 'tanh']),
 IntegerDistribution(name='n_iter', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=None, low=100, high=1000, step=100),
 FloatDistribution(name='generator_dropout', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=None, low=0.0, high=0.2),
 IntegerDistribution(name='discriminator_n_layers_hidden', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=None, low=1, high=4, step=1),
 IntegerDistribution(name='discriminator_n_units_hidden', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=None, low=50, high=150, step=50),
 CategoricalDistribution(name='discriminator_nonlin', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=elu           0.25
 leaky_relu    0.25
 relu          0.25
 tanh          0.25
 dtype: float64, choices=['elu', 'leaky_relu', 'relu', 'tanh']),
 IntegerDistribution(name='discriminator_n_iter', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=None, low=1, high=5, step=1),
 FloatDistribution(name='discriminator_dropout', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=None, low=0.0, high=0.2),
 CategoricalDistribution(name='lr', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=0.0001    0.333333
 0.0002    0.333333
 0.0010    0.333333
 dtype: float64, choices=[0.0001, 0.0002, 0.001]),
 CategoricalDistribution(name='weight_decay', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=0.0001    0.5
 0.0010    0.5
 dtype: float64, choices=[0.0001, 0.001]),
 CategoricalDistribution(name='batch_size', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=100    0.333333
 200    0.333333
 500    0.333333
 dtype: float64, choices=[100, 200, 500]),
 IntegerDistribution(name='encoder_max_clusters', data=None, random_state=None, sampling_strategy='marginal', marginal_distribution=None, low=2, high=20, step=1)]

Use a trial to suggest a set of hyperparameters.

In [6]:
import optuna
from synthcity.utils.optuna_sample import suggest_all

trial = optuna.create_study().ask()
params = suggest_all(trial, plugin_cls.hyperparameter_space())
# params["n_iter"] = 100 # speed up
params

{'generator_n_layers_hidden': 1,
 'generator_n_units_hidden': 100,
 'generator_nonlin': 'relu',
 'n_iter': 200,
 'generator_dropout': 0.16423752147137477,
 'discriminator_n_layers_hidden': 3,
 'discriminator_n_units_hidden': 100,
 'discriminator_nonlin': 'elu',
 'discriminator_n_iter': 5,
 'discriminator_dropout': 0.039818031175037905,
 'lr': 0.0002,
 'weight_decay': 0.0001,
 'batch_size': 500,
 'encoder_max_clusters': 6}

Evaluate the plugin with the suggested hyperparameters.

In [17]:
from synthcity.benchmark import Benchmarks

plugin = plugin_cls(**params).fit(train_loader)
report = Benchmarks.evaluate(
    [("trial", "ctgan", params)],
    train_loader, # Benchmarks.evaluate will split out a validation set
    repeats=1,
    # metrics={"detection": ["detection_xgb"]}
)
report["trial"]

100%|██████████| 200/200 [00:12<00:00, 16.46it/s]
[2025-11-23T18:14:44.208254+0000][3798][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 200/200 [00:10<00:00, 18.98it/s]

,min,max,mean,stddev,median,iqr,rounds,errors,durations,direction
sanity.data_mismatch.score,0.000000,0.000000,0.000000,0.0,0.000000,0.0,1,0,0.00,minimize
sanity.common_rows_proportion.score,0.000000,0.000000,0.000000,0.0,0.000000,0.0,1,0,0.00,minimize
sanity.nearest_syn_neighbor_distance.mean,0.258148,0.258148,0.258148,0.0,0.258148,0.0,1,0,0.00,minimize
sanity.close_values_probability.score,0.439024,0.439024,0.439024,0.0,0.439024,0.0,1,0,0.00,maximize
sanity.distant_values_probability.score,0.006098,0.006098,0.006098,0.0,0.006098,0.0,1,0,0.00,minimize
stats.jensenshannon_dist.marginal,0.044006,0.044006,0.044006,0.0,0.044006,0.0,1,0,0.06,minimize
stats.chi_squared_test.marginal,0.627289,0.627289,0.627289,0.0,0.627289,0.0,1,0,0.02,maximize
stats.inv_kl_divergence.marginal,0.696748,0.696748,0.696748,0.0,0.696748,0.0,1,0,0.01,maximize
stats.ks_test.marginal,0.643728,0.643728,0.643728,0.0,0.643728,0.0,1,0,0.01,maximize
stats.max_mean_discrepancy.joint,0.014872,0.014872,0.014872,0.0,0.014872,0.0,1,0,0.01,minimize
stats.wasserstein_dist.joint,1.070127,1.070127,1.070127,0.0,1.070127,0.0,1,0,0.25,minimize
stats.prdc.precision,0.713415,0.713415,0.713415,0.0,0.713415,0.0,1,0,0.01,maximize
stats.prdc.recall,0.792683,0.792683,0.792683,0.0,0.792683,0.0,1,0,0.01,maximize
stats.prdc.density,0.270732,0.270732,0.270732,0.0,0.270732,0.0,1,0,0.01,maximize
stats.prdc.coverage,0.213415,0.213415,0.213415,0.0,0.213415,0.0,1,0,0.01,maximize
stats.alpha_precision.delta_precision_alpha_OC,0.337805,0.337805,0.337805,0.0,0.337805,0.0,1,0,1.19,maximize
stats.alpha_precision.delta_coverage_beta_OC,0.067886,0.067886,0.067886,0.0,0.067886,0.0,1,0,1.19,maximize
stats.alpha_precision.authenticity_OC,0.920732,0.920732,0.920732,0.0,0.920732,0.0,1,0,1.19,maximize
stats.alpha_precision.delta_precision_alpha_naive,0.090650,0.090650,0.090650,0.0,0.090650,0.0,1,0,1.19,maximize
stats.alpha_precision.delta_coverage_beta_naive,0.016667,0.016667,0.016667,0.0,0.016667,0.0,1,0,1.19,maximize
stats.alpha_precision.authenticity_naive,0.981707,0.981707,0.981707,0.0,0.981707,0.0,1,0,1.19,maximize
performance.linear_model.gt,0.875761,0.875761,0.875761,0.0,0.875761,0.0,1,0,0.38,maximize
performance.linear_model.syn_id,0.407495,0.407495,0.407495,0.0,0.407495,0.0,1,0,0.38,maximize
performance.linear_model.syn_ood,0.360294,0.360294,0.360294,0.0,0.360294,0.0,1,0,0.38,maximize
performance.mlp.gt,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,3.07,maximize
performance.mlp.syn_id,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,3.07,maximize
performance.mlp.syn_ood,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,3.07,maximize
performance.xgb.gt,0.898373,0.898373,0.898373,0.0,0.898373,0.0,1,0,0.53,maximize
performance.xgb.syn_id,0.419034,0.419034,0.419034,0.0,0.419034,0.0,1,0,0.53,maximize
performance.xgb.syn_ood,0.422794,0.422794,0.422794,0.0,0.422794,0.0,1,0,0.53,maximize
performance.linear_model_augmentation.gt,0.875761,0.875761,0.875761,0.0,0.875761,0.0,1,0,0.29,maximize
performance.linear_model_augmentation.aug_ood,0.360294,0.360294,0.360294,0.0,0.360294,0.0,1,0,0.29,maximize
performance.mlp_augmentation.gt,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,3.25,maximize
performance.mlp_augmentation.aug_ood,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,3.25,maximize
performance.xgb_augmentation.gt,0.898373,0.898373,0.898373,0.0,0.898373,0.0,1,0,0.36,maximize
performance.xgb_augmentation.aug_ood,0.422794,0.422794,0.422794,0.0,0.422794,0.0,1,0,0.36,maximize
performance.feat_rank_distance.corr,0.005693,0.005693,0.005693,0.0,0.005693,0.0,1,0,0.14,minimize
performance.feat_rank_distance.pvalue,0.962916,0.962916,0.962916,0.0,0.962916,0.0,1,0,0.14,minimize
detection.detection_xgb.mean,0.990416,0.990416,0.990416,0.0,0.990416,0.0,1,0,0.08,minimize
detection.detection_mlp.mean,0.599265,0.599265,0.599265,0.0,0.599265,0.0,1,0,1.29,minimize
detection.detection_gmm.mean,0.520569,0.520569,0.520569,0.0,0.520569,0.0,1,0,0.16,minimize
detection.detection_linear.mean,0.989451,0.989451,0.989451,0.0,0.989451,0.0,1,0,12.07,minimize
privacy.delta-presence.score,18.000000,18.000000,18.000000,0.0,18.000000,0.0,1,0,0.02,maximize
privacy.k-anonymization.gt,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.03,maximize
privacy.k-anonymization.syn,2.000000,2.000000,2.000000,0.0,2.000000,0.0,1,0,0.03,maximize
privacy.k-map.score,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.02,maximize
privacy.distinct l-diversity.gt,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.06,maximize
privacy.distinct l-diversity.syn,2.000000,2.000000,2.000000,0.0,2.000000,0.0,1,0,0.06,maximize
privacy.identifiability_score.score,0.048780,0.048780,0.048780,0.0,0.048780,0.0,1,0,0.02,minimize
privacy.identifiability_score.score_OC,0.054878,0.054878,0.054878,0.0,0.054878,0.0,1,0,0.02,minimize
privacy.DomiasMIA_BNAF.accuracy,0.015015,0.015015,0.015015,0.0,0.015015,0.0,1,0,160.69,minimize
privacy.DomiasMIA_BNAF.aucroc,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,160.69,minimize
privacy.DomiasMIA_prior.accuracy,0.496997,0.496997,0.496997,0.0,0.496997,0.0,1,0,0.15,minimize
privacy.DomiasMIA_prior.aucroc,0.422713,0.422713,0.422713,0.0,0.422713,0.0,1,0,0.15,minimize

Create an Optuna study and optimize the hyperparameters.

In [7]:
from synthcity.benchmark import Benchmarks

def objective(trial: optuna.Trial):
    hp_space = Plugins().get("ctgan").hyperparameter_space()
    params = suggest_all(trial, hp_space)
    ID = f"trial_{trial.number}"
    try:
        report = Benchmarks.evaluate(
            [(ID, "ctgan", params)],
            train_loader,
            repeats=1,
            metrics={"stats": ["jensenshannon_dist"]},
        )
    except Exception:
        raise optuna.TrialPruned()

    score = report[ID]["mean"].mean()
    return score

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=5)
best_params = study.best_params

[2025-11-23T21:03:08.661980+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T21:03:08.701050+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
 90%|████████▉ | 449/500 [00:59<00:06,  7.54it/s]
[2025-11-23T21:04:10.078038+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T21:04:10.086046+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
 50%|████▉     | 499/1000 [01:11<01:11,  6.99it/s]
[2025-11-23T21:05:22.743922+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T21:05:22.758624+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 300/300 [00:56<00:00,  5.27it/s]
[2025-11-23T21:06:21.537494+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T21:06:21.545513+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 500/500 [00:50<00:00,  9.81it/s]
[2025-11-23T21:07:13.676037+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T21:07:13.683986+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 800/800 [00:53<00:00, 14.90it/s]

In [ ]:
# import pandas as pd

# def objective(trial: optuna.Trial):
#     hp_space = Plugins().get("ctgan").hyperparameter_space()
#     params = suggest_all(trial, hp_space)
#     ID = f"trial_{trial.number}"
#     try:
#         report = Benchmarks.evaluate(
#             [(ID, "ctgan", params)],
#             train_loader,
#             repeats=1,
#             metrics={"detection": ["detection_xgb"]},
#         )
#     except Exception as e: # invalid set of params
#         print(f"{type(e).__name__}: {e}")
#         print(params)
#         raise optuna.TrialPruned()
#     score = report[ID].query('direction == "minimize"')["mean"].mean()
#     # df = report[ID]
#     # minimize metrics
#     # minimize_vals = df.query('direction == "minimize"')["mean"]
#     # maximize metrics → turn into minimize form by negating
#     # maximize_vals = -df.query('direction == "maximize"')["mean"]
#     # final scalar objective
#     # score = pd.concat([minimize_vals, maximize_vals]).mean()

#     return score

# study = optuna.create_study(direction="minimize")
# study.optimize(objective, n_trials=2)
# study.best_params

[2025-11-23T19:12:12.612630+0000][3798][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T19:12:12.738518+0000][3798][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 200/200 [01:13<00:00,  2.73it/s]
[2025-11-23T19:13:28.214185+0000][3798][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T19:13:28.223149+0000][3798][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 500/500 [01:23<00:00,  6.01it/s]

{'generator_n_layers_hidden': 2,
 'generator_n_units_hidden': 150,
 'generator_nonlin': 'relu',
 'n_iter': 500,
 'generator_dropout': 0.13266420537712784,
 'discriminator_n_layers_hidden': 2,
 'discriminator_n_units_hidden': 150,
 'discriminator_nonlin': 'tanh',
 'discriminator_n_iter': 3,
 'discriminator_dropout': 0.08724841559085626,
 'lr': 0.0002,
 'weight_decay': 0.001,
 'batch_size': 200,
 'encoder_max_clusters': 18}

Visualize the study.

In [ ]:
from optuna.visualization import (plot_contour,
                                  plot_edf,
                                  plot_optimization_history,
                                  plot_parallel_coordinate,
                                  plot_param_importances,
                                  plot_slice)

plot_optimization_history(study)

In [ ]:
# visualize high-dimensional parameter relationships
plot_parallel_coordinate(study)

In [ ]:
# visualize hyperparameter relationships
fig = plot_contour(study, params=["batch_size", "lr", "generator_n_layers_hidden", "discriminator_n_layers_hidden"])
fig.update_layout(width=800, height=800)

In [ ]:
# visualize individual hyperparameters as slice plot
plot_slice(study)

In [ ]:
# visualize parameter importances
plot_param_importances(study)

In [ ]:
# learn which hyperparameters are affecting the trial duration with hyperparameter importance
optuna.visualization.plot_param_importances(
    study, target=lambda t: t.duration.total_seconds(), target_name="duration"
)

In [ ]:
# visualize empirical distribution function of the objective
plot_edf(study)

Test performance of the optimized plugin.

In [8]:
best_params = study.best_params
report = Benchmarks.evaluate(
    [("test", "ctgan", best_params)],
    train_loader,
    test_loader,
    repeats=1,
    # metrics={"detection": ["detection_mlp", "detection_xgb"]},
)
Benchmarks.print(report)

[2025-11-23T21:08:28.999305+0000][79342][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 800/800 [00:53<00:00, 15.01it/s]

Plugin : test

,min,max,mean,stddev,median,iqr,rounds,errors,durations
sanity.data_mismatch.score,0.000000,0.000000,0.000000,0.0,0.000000,0.0,1,0,0.00
sanity.common_rows_proportion.score,0.000000,0.000000,0.000000,0.0,0.000000,0.0,1,0,0.01
sanity.nearest_syn_neighbor_distance.mean,0.058598,0.058598,0.058598,0.0,0.058598,0.0,1,0,0.01
sanity.close_values_probability.score,0.985366,0.985366,0.985366,0.0,0.985366,0.0,1,0,0.00
sanity.distant_values_probability.score,0.004878,0.004878,0.004878,0.0,0.004878,0.0,1,0,0.00
stats.jensenshannon_dist.marginal,0.010985,0.010985,0.010985,0.0,0.010985,0.0,1,0,0.09
stats.chi_squared_test.marginal,0.629321,0.629321,0.629321,0.0,0.629321,0.0,1,0,0.03
stats.inv_kl_divergence.marginal,0.901631,0.901631,0.901631,0.0,0.901631,0.0,1,0,0.02
stats.ks_test.marginal,0.920906,0.920906,0.920906,0.0,0.920906,0.0,1,0,0.03
stats.max_mean_discrepancy.joint,0.011993,0.011993,0.011993,0.0,0.011993,0.0,1,0,0.05
stats.wasserstein_dist.joint,0.242395,0.242395,0.242395,0.0,0.242395,0.0,1,0,0.12
stats.prdc.precision,0.980488,0.980488,0.980488,0.0,0.980488,0.0,1,0,0.01
stats.prdc.recall,0.936585,0.936585,0.936585,0.0,0.936585,0.0,1,0,0.01
stats.prdc.density,0.931707,0.931707,0.931707,0.0,0.931707,0.0,1,0,0.01
stats.prdc.coverage,0.936585,0.936585,0.936585,0.0,0.936585,0.0,1,0,0.01
stats.alpha_precision.delta_precision_alpha_OC,0.856630,0.856630,0.856630,0.0,0.856630,0.0,1,0,0.15
stats.alpha_precision.delta_coverage_beta_OC,0.318699,0.318699,0.318699,0.0,0.318699,0.0,1,0,0.15
stats.alpha_precision.authenticity_OC,0.653659,0.653659,0.653659,0.0,0.653659,0.0,1,0,0.15
stats.alpha_precision.delta_precision_alpha_naive,0.949941,0.949941,0.949941,0.0,0.949941,0.0,1,0,0.15
stats.alpha_precision.delta_coverage_beta_naive,0.321301,0.321301,0.321301,0.0,0.321301,0.0,1,0,0.15
stats.alpha_precision.authenticity_naive,0.668293,0.668293,0.668293,0.0,0.668293,0.0,1,0,0.15
performance.linear_model.gt,0.902022,0.902022,0.902022,0.0,0.902022,0.0,1,0,0.31
performance.linear_model.syn_id,0.890763,0.890763,0.890763,0.0,0.890763,0.0,1,0,0.31
performance.linear_model.syn_ood,0.885714,0.885714,0.885714,0.0,0.885714,0.0,1,0,0.31
performance.mlp.gt,0.642647,0.642647,0.642647,0.0,0.642647,0.0,1,0,3.24
performance.mlp.syn_id,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,3.24
performance.mlp.syn_ood,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,3.24
performance.xgb.gt,0.915487,0.915487,0.915487,0.0,0.915487,0.0,1,0,0.55
performance.xgb.syn_id,0.852436,0.852436,0.852436,0.0,0.852436,0.0,1,0,0.55
performance.xgb.syn_ood,0.878571,0.878571,0.878571,0.0,0.878571,0.0,1,0,0.55
performance.linear_model_augmentation.gt,0.902022,0.902022,0.902022,0.0,0.902022,0.0,1,0,0.36
performance.linear_model_augmentation.aug_ood,0.885714,0.885714,0.885714,0.0,0.885714,0.0,1,0,0.36
performance.mlp_augmentation.gt,0.642647,0.642647,0.642647,0.0,0.642647,0.0,1,0,3.25
performance.mlp_augmentation.aug_ood,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,3.25
performance.xgb_augmentation.gt,0.915487,0.915487,0.915487,0.0,0.915487,0.0,1,0,0.41
performance.xgb_augmentation.aug_ood,0.878571,0.878571,0.878571,0.0,0.878571,0.0,1,0,0.41
performance.feat_rank_distance.corr,0.035496,0.035496,0.035496,0.0,0.035496,0.0,1,0,0.12
performance.feat_rank_distance.pvalue,0.744538,0.744538,0.744538,0.0,0.744538,0.0,1,0,0.12
detection.detection_xgb.mean,0.787864,0.787864,0.787864,0.0,0.787864,0.0,1,0,0.15
detection.detection_mlp.mean,0.508507,0.508507,0.508507,0.0,0.508507,0.0,1,0,1.52
detection.detection_gmm.mean,0.508566,0.508566,0.508566,0.0,0.508566,0.0,1,0,0.45
detection.detection_linear.mean,0.617371,0.617371,0.617371,0.0,0.617371,0.0,1,0,29.34
privacy.delta-presence.score,4.000000,4.000000,4.000000,0.0,4.000000,0.0,1,0,0.38
privacy.k-anonymization.gt,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.08
privacy.k-anonymization.syn,4.000000,4.000000,4.000000,0.0,4.000000,0.0,1,0,0.08
privacy.k-map.score,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.05
privacy.distinct l-diversity.gt,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.21
privacy.distinct l-diversity.syn,4.000000,4.000000,4.000000,0.0,4.000000,0.0,1,0,0.21
privacy.identifiability_score.score,0.278049,0.278049,0.278049,0.0,0.278049,0.0,1,0,1.14
privacy.identifiability_score.score_OC,0.292683,0.292683,0.292683,0.0,0.292683,0.0,1,0,1.14
privacy.DomiasMIA_BNAF.accuracy,0.232733,0.232733,0.232733,0.0,0.232733,0.0,1,0,187.51
privacy.DomiasMIA_BNAF.aucroc,0.482470,0.482470,0.482470,0.0,0.482470,0.0,1,0,187.51
privacy.DomiasMIA_prior.accuracy,0.492492,0.492492,0.492492,0.0,0.492492,0.0,1,0,0.08
privacy.DomiasMIA_prior.aucroc,0.354192,0.354192,0.354192,0.0,0.354192,0.0,1,0,0.08

In [20]:
best_params

{'generator_n_layers_hidden': 2,
 'generator_n_units_hidden': 150,
 'generator_nonlin': 'relu',
 'n_iter': 500,
 'generator_dropout': 0.13266420537712784,
 'discriminator_n_layers_hidden': 2,
 'discriminator_n_units_hidden': 150,
 'discriminator_nonlin': 'tanh',
 'discriminator_n_iter': 3,
 'discriminator_dropout': 0.08724841559085626,
 'lr': 0.0002,
 'weight_decay': 0.001,
 'batch_size': 200,
 'encoder_max_clusters': 18}

In [21]:
plugin.generate(50, **best_params)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,51,1,2,112,473,0,2,192,0,4.301238,0,2,2,0
1,62,1,2,109,298,0,1,202,0,2.113944,1,1,2,0
2,52,0,0,117,206,0,1,199,1,6.200000,2,2,3,0
3,47,1,2,118,400,0,2,155,1,0.000000,2,1,2,0
4,60,0,2,131,207,1,0,174,0,1.905392,1,0,3,1
5,62,1,2,124,285,0,0,173,1,0.850394,2,2,2,0
6,65,0,3,113,564,0,1,194,0,2.904682,2,2,3,0
7,49,0,3,104,330,0,1,202,1,0.760005,1,1,2,1
8,47,0,2,104,312,0,1,187,1,2.750711,1,3,3,0
9,50,0,0,129,253,1,2,146,0,2.059770,1,0,1,0
10,41,1,2,121,292,0,1,132,0,1.581193,1,0,0,0
11,59,0,1,116,194,0,1,185,0,4.500824,2,0,2,0
12,50,1,2,104,413,0,1,202,1,6.200000,1,2,1,0
13,59,0,3,109,301,0,1,191,0,4.260824,1,0,3,0
14,43,1,2,136,199,0,0,153,0,0.160256,2,2,3,0
15,56,1,2,139,378,0,0,150,0,1.834335,2,0,3,1
16,56,1,2,104,375,0,1,173,1,1.594636,1,0,2,0
17,42,0,2,117,378,0,1,182,1,2.238000,1,0,0,0
18,51,1,2,117,324,0,0,202,0,4.600564,2,1,3,0
19,56,0,3,111,241,0,1,169,0,0.620260,0,1,1,1
20,64,0,2,117,413,0,1,202,0,2.157398,0,0,3,0
21,77,1,2,105,340,0,1,192,0,0.401813,1,0,2,0
22,57,0,2,107,352,0,1,175,1,2.166180,1,2,1,1
23,52,1,0,127,310,0,0,180,0,1.658450,1,0,3,0
24,63,0,2,135,327,1,0,170,1,0.000000,0,4,2,0
25,39,0,1,125,272,1,0,174,1,6.200000,2,0,2,1
26,49,1,2,134,373,0,1,201,1,3.413432,2,4,3,0
27,59,1,3,106,413,0,0,202,1,2.738858,1,1,3,1
28,74,1,0,121,352,1,1,202,0,1.959273,1,0,3,0
29,61,0,2,119,336,0,1,183,0,0.399249,1,3,2,1
30,50,1,3,109,309,0,0,202,1,3.608647,1,4,2,0
31,38,1,2,117,291,0,1,202,1,1.657324,0,0,2,0
32,67,1,2,113,259,1,0,163,0,2.983061,2,2,1,0
33,54,1,3,109,307,0,0,196,0,6.200000,1,3,2,0
34,73,0,0,119,267,0,1,160,0,3.506882,2,1,0,1
35,68,0,2,125,352,0,1,185,0,0.297879,0,0,1,0
36,51,0,2,133,275,0,1,177,1,6.200000,1,4,0,1
37,52,0,2,112,315,0,2,151,1,3.993129,1,1,3,0
38,50,1,2,109,413,0,1,202,1,1.245236,1,0,3,0
39,58,1,0,104,217,0,2,170,1,2.108340,1,0,3,0
40,66,1,1,129,223,0,1,170,0,1.878642,1,3,3,0
41,67,0,2,109,345,0,1,202,0,0.257975,2,3,1,0
42,64,0,2,110,349,0,2,202,0,1.764401,0,0,3,0
43,45,1,3,117,317,0,1,150,0,0.663394,1,1,2,1
44,71,1,1,122,373,0,0,186,0,2.874955,1,0,3,0
45,60,1,2,104,302,0,1,196,0,3.613350,1,0,0,0
46,71,1,1,118,318,0,1,197,1,0.923658,2,0,2,0
47,57,0,2,117,275,1,1,202,0,1.952088,1,2,2,0
48,56,0,1,115,271,0,1,187,1,0.186749,1,2,3,0
49,59,0,2,126,212,1,0,198,0,2.980710,1,3,3,0

Metrics we will use in the study.

1. Fidelity:
    - Jensen-Shannon distance (marginal)
    - Wasserstein distance (joint)
    - PRDC (precision/recall)

2. Utility
    - Train on synthetic -> test on real (TSTR) performance. Using a consistent ML model (e.g., XGBoost or Logistic Regression)

3. Privacy
    - Nearest-neighbor distance
    - Common rows proportion
    - Membership inference attach AUC
    - etc.

In [ ]:
from src.run_experiment import run_experiment

run_experiment("rtvae", "heart.csv")

/workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[KeOps] Warning : CUDA libraries not found or could not be loaded; Switching to CPU only.
=== Optimizing hyperparameters ===

[2025-11-23T23:01:43.713814+0000][137330][CRITICAL] Error importing TabularGoggle: No module named 'dgl'
[2025-11-23T23:01:43.718043+0000][137330][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T23:01:45.190043+0000][137330][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 400/400 [01:02<00:00,  6.43it/s]
[2025-11-23T23:02:48.740125+0000][137330][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T23:02:48.748522+0000][137330][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 200/200 [01:11<00:00,  2.80it/s]
[2025-11-23T23:04:01.951706+0000][137330][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T23:04:01.961650+0000][137330][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 100/100 [00:55<00:00,  1.80it/s]
[2025-11-23T23:04:59.036624+0000][137330][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T23:04:59.044692+0000][137330][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 300/300 [00:16<00:00, 18.36it/s]
[2025-11-23T23:05:16.653691+0000][137330][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-23T23:05:16.661055+0000][137330][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py
100%|██████████| 500/500 [06:15<00:00,  1.33it/s]
[2025-11-23T23:11:34.674606+0000][137330][CRITICAL] module disabled: /workspaces/synth_tab_health_data/.venv/lib/python3.12/site-packages/synthcity/plugins/generic/plugin_goggle.py

=== Best parameters ===
{'n_iter': 200, 'lr': 0.001, 'decoder_n_layers_hidden': 4, 'weight_decay': 0.001, 'batch_size': 512, 'n_units_embedding': 450, 'decoder_n_units_hidden': 50, 'decoder_nonlin': 'elu', 'decoder_dropout': 0.1402374823431258, 'encoder_n_layers_hidden': 1, 'encoder_n_units_hidden': 400, 'encoder_nonlin': 'elu', 'encoder_dropout': 0.12412264944660674}

=== Evaluating all metrics with best parameters ===

100%|██████████| 200/200 [01:08<00:00,  2.94it/s]

Plugin : test

,min,max,mean,stddev,median,iqr,rounds,errors,durations
sanity.data_mismatch.score,0.000000,0.000000,0.000000,0.0,0.000000,0.0,1,0,0.00
sanity.common_rows_proportion.score,0.000000,0.000000,0.000000,0.0,0.000000,0.0,1,0,0.01
sanity.nearest_syn_neighbor_distance.mean,0.098060,0.098060,0.098060,0.0,0.098060,0.0,1,0,0.01
sanity.close_values_probability.score,0.926829,0.926829,0.926829,0.0,0.926829,0.0,1,0,0.00
sanity.distant_values_probability.score,0.004878,0.004878,0.004878,0.0,0.004878,0.0,1,0,0.00
stats.jensenshannon_dist.marginal,0.022204,0.022204,0.022204,0.0,0.022204,0.0,1,0,0.06
stats.chi_squared_test.marginal,0.462032,0.462032,0.462032,0.0,0.462032,0.0,1,0,0.02
stats.inv_kl_divergence.marginal,0.686190,0.686190,0.686190,0.0,0.686190,0.0,1,0,0.01
stats.ks_test.marginal,0.841812,0.841812,0.841812,0.0,0.841812,0.0,1,0,0.01
stats.max_mean_discrepancy.joint,0.012886,0.012886,0.012886,0.0,0.012886,0.0,1,0,0.02
stats.wasserstein_dist.joint,0.272136,0.272136,0.272136,0.0,0.272136,0.0,1,0,0.08
stats.prdc.precision,0.946341,0.946341,0.946341,0.0,0.946341,0.0,1,0,0.01
stats.prdc.recall,0.234146,0.234146,0.234146,0.0,0.234146,0.0,1,0,0.01
stats.prdc.density,0.965854,0.965854,0.965854,0.0,0.965854,0.0,1,0,0.01
stats.prdc.coverage,0.419512,0.419512,0.419512,0.0,0.419512,0.0,1,0,0.01
stats.alpha_precision.delta_precision_alpha_OC,0.850586,0.850586,0.850586,0.0,0.850586,0.0,1,0,0.11
stats.alpha_precision.delta_coverage_beta_OC,0.276748,0.276748,0.276748,0.0,0.276748,0.0,1,0,0.11
stats.alpha_precision.authenticity_OC,0.756098,0.756098,0.756098,0.0,0.756098,0.0,1,0,0.11
stats.alpha_precision.delta_precision_alpha_naive,0.846504,0.846504,0.846504,0.0,0.846504,0.0,1,0,0.11
stats.alpha_precision.delta_coverage_beta_naive,0.317724,0.317724,0.317724,0.0,0.317724,0.0,1,0,0.11
stats.alpha_precision.authenticity_naive,0.707317,0.707317,0.707317,0.0,0.707317,0.0,1,0,0.11
performance.linear_model.gt,0.902022,0.902022,0.902022,0.0,0.902022,0.0,1,0,0.33
performance.linear_model.syn_id,0.901011,0.901011,0.901011,0.0,0.901011,0.0,1,0,0.33
performance.linear_model.syn_ood,0.883333,0.883333,0.883333,0.0,0.883333,0.0,1,0,0.33
performance.mlp.gt,0.642647,0.642647,0.642647,0.0,0.642647,0.0,1,0,3.62
performance.mlp.syn_id,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,3.62
performance.mlp.syn_ood,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,3.62
performance.xgb.gt,0.915487,0.915487,0.915487,0.0,0.915487,0.0,1,0,0.44
performance.xgb.syn_id,0.845037,0.845037,0.845037,0.0,0.845037,0.0,1,0,0.44
performance.xgb.syn_ood,0.916667,0.916667,0.916667,0.0,0.916667,0.0,1,0,0.44
performance.linear_model_augmentation.gt,0.902022,0.902022,0.902022,0.0,0.902022,0.0,1,0,0.29
performance.linear_model_augmentation.aug_ood,0.883333,0.883333,0.883333,0.0,0.883333,0.0,1,0,0.29
performance.mlp_augmentation.gt,0.642647,0.642647,0.642647,0.0,0.642647,0.0,1,0,3.47
performance.mlp_augmentation.aug_ood,0.500000,0.500000,0.500000,0.0,0.500000,0.0,1,0,3.47
performance.xgb_augmentation.gt,0.915487,0.915487,0.915487,0.0,0.915487,0.0,1,0,0.39
performance.xgb_augmentation.aug_ood,0.916667,0.916667,0.916667,0.0,0.916667,0.0,1,0,0.39
performance.feat_rank_distance.corr,-0.167687,-0.167687,0.001000,0.0,-0.167687,0.0,1,0,0.15
performance.feat_rank_distance.pvalue,0.123717,0.123717,0.123717,0.0,0.123717,0.0,1,0,0.15
detection.detection_xgb.mean,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.08
detection.detection_mlp.mean,0.549613,0.549613,0.549613,0.0,0.549613,0.0,1,0,1.47
detection.detection_gmm.mean,0.521475,0.521475,0.521475,0.0,0.521475,0.0,1,0,0.14
detection.detection_linear.mean,0.714337,0.714337,0.714337,0.0,0.714337,0.0,1,0,21.53
privacy.delta-presence.score,24.000000,24.000000,24.000000,0.0,24.000000,0.0,1,0,0.11
privacy.k-anonymization.gt,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.03
privacy.k-anonymization.syn,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.03
privacy.k-map.score,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.02
privacy.distinct l-diversity.gt,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.06
privacy.distinct l-diversity.syn,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1,0,0.06
privacy.identifiability_score.score,0.107317,0.107317,0.107317,0.0,0.107317,0.0,1,0,0.19
privacy.identifiability_score.score_OC,0.278049,0.278049,0.278049,0.0,0.278049,0.0,1,0,0.19
privacy.DomiasMIA_BNAF.accuracy,0.217718,0.217718,0.217718,0.0,0.217718,0.0,1,0,172.25
privacy.DomiasMIA_BNAF.aucroc,0.420579,0.420579,0.420579,0.0,0.420579,0.0,1,0,172.25
privacy.DomiasMIA_prior.accuracy,0.493994,0.493994,0.493994,0.0,0.493994,0.0,1,0,0.10
privacy.DomiasMIA_prior.aucroc,0.360137,0.360137,0.360137,0.0,0.360137,0.0,1,0,0.10

Describe models in chronological order, timeline.