# Evaluation of Synthetic Data Generation Methods for Tabular Health Data

## Models Evaluated

In this study we evaluate both probabilistic and generative synthetic data generation methods on tabular health data,
using implementations from **Synthetic Data Vault (SDV)** and **synthcity** Python libraries.

For each model we also try a differentially private (DP) version and later evaluate both.

### Probabilistic

1. **Gaussian Copulas**
    - `GaussianCopulaSynthesizer`
    - `DPGCSynthesizer` (DP version)
2. **Bayesian Networks**
    - `BayesianNetworkPlugin`
    - `PrivBayes` (DP version)

### Generative

1. **Generative Adversarial Networks**
    - `CTGAN`
    - DP variants: `DP-GAN`, `PATEGAN`, `AdsGAN`
2. **Variational Auto-Encoders**
    - `TVAE`, `RTVAE`
    - DP variants
3. **Normalizing Flows**
4. **Autoregressive / Tree-Based Models**
    - ARF (Adversarial Random Forests)
6. **Diffusion Models**
    - `TabDDPM` (DP)
    - `TableDiffusion` (DP)

## Data

A public clinical dataset **Heart Disease** from **UC Irvine Machine Learning Repository** is used in this study.

In [1]:
%pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2025.10.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [1]:
from ucimlrepo import fetch_ucirepo

heart_disease = fetch_ucirepo(id=45)

X = heart_disease.data.features
y = heart_disease.data.targets

X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110,264,0,0,132,0,1.2,2,0.0,7.0
299,68,1,4,144,193,1,0,141,0,3.4,2,2.0,7.0
300,57,1,4,130,131,0,0,115,1,1.2,2,1.0,7.0
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,3.0
302,38,1,3,138,175,0,0,173,0,0.0,1,NaN,3.0

# Generative Models

## Generative Adversarial Network (GAN)

In this section we use GAN models to generate synthetic datasets from our original data.

### General Idea

There are two components - generator and discriminator. Generator creates a realistic synthetic row of tabular data with random noise applied. Discriminator acts as a binary classifier deciding whether the provided row is real or fake (0-1), taking either real or synthetic row as an input.

`[insert GAN loss function here]`

Discriminator (D) wants to classify correctly real samples (high probability) and fake samples (low probability).

Generator (G) wants to make Discrimator (D) classify fake samples as real.

### GAN on Tabular Data

Conditional Tabular Generative Adversarial Network (CTGAN) can explicitly condition the data generation process on specific categorical variables.

A typical CTGAN training loop:

1. Sample real batch from dataset.
2. Sample noise z.
3. Generator creates synthetic samples G(z).
4. Discriminator trains on:
    - real samples → label 1
    - fake samples → label 0
5. Generator trains to fool the discriminator:
    - update G so D(G(z)) → 1
6. Apply conditional constraints (CTGAN)
7. Repeat until convergence.

In [3]:
%pip install torch==2.2.2

Requirement already satisfied: torch==2.2.2 in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (3.20.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (4.15.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (2.8.8)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2) (12.1.105)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2) (12.6.85)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.2.2) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->torch==2.2.2) (1.3.0)

In [11]:
%pip install synthcity

Requirement already satisfied: synthcity in /usr/local/lib/python3.12/dist-packages (0.2.12)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.12/dist-packages (from synthcity) (8.7.0)
Requirement already satisfied: pandas>=2.1 in /usr/local/lib/python3.12/dist-packages (from synthcity) (2.2.2)
Requirement already satisfied: torch<2.3,>=2.1 in /usr/local/lib/python3.12/dist-packages (from synthcity) (2.2.2)
Requirement already satisfied: scikit-learn>=1.2 in /usr/local/lib/python3.12/dist-packages (from synthcity) (1.6.1)
Requirement already satisfied: nflows>=0.14 in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.14)
Requirement already satisfied: numpy<2.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from synthcity) (1.26.4)
Requirement already satisfied: lifelines<0.30.0,>=0.29.0 in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.29.0)
Requirement already satisfied: opacus>=1.3 in /usr/local/lib/python3.12/dist-packages (from synthcity) (1.5.3)
Requirement already satisfied: networkx<3.0,>2.0 in /usr/local/lib/python3.12/dist-packages (from synthcity) (2.8.8)
Requirement already satisfied: decaf-synthetic-data>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.1.7)
Requirement already satisfied: optuna>=3.1 in /usr/local/lib/python3.12/dist-packages (from synthcity) (4.6.0)
Requirement already satisfied: shap in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.49.1)
Requirement already satisfied: tenacity in /usr/local/lib/python3.12/dist-packages (from synthcity) (8.5.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from synthcity) (4.67.1)
Requirement already satisfied: loguru in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.7.3)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from synthcity) (2.11.10)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from synthcity) (3.1.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from synthcity) (1.16.3)
Requirement already satisfied: xgboost<3.0.0 in /usr/local/lib/python3.12/dist-packages (from synthcity) (2.1.4)
Requirement already satisfied: geomloss in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.2.6)
Requirement already satisfied: pgmpy<1.0 in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.1.26)
Requirement already satisfied: redis in /usr/local/lib/python3.12/dist-packages (from synthcity) (7.0.1)
Requirement already satisfied: pycox in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.3.0)
Requirement already satisfied: xgbse>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.3.3)
Requirement already satisfied: pykeops in /usr/local/lib/python3.12/dist-packages (from synthcity) (2.3)
Requirement already satisfied: fflows in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.0.3)
Requirement already satisfied: monai in /usr/local/lib/python3.12/dist-packages (from synthcity) (1.4.0)
Requirement already satisfied: tsai in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.4.0)
Requirement already satisfied: be-great>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.0.9)
Requirement already satisfied: arfpy in /usr/local/lib/python3.12/dist-packages (from synthcity) (0.1.1)
Requirement already satisfied: fastcore<1.8 in /usr/local/lib/python3.12/dist-packages (from synthcity) (1.7.29)
Requirement already satisfied: fastai<2.8 in /usr/local/lib/python3.12/dist-packages (from synthcity) (2.7.19)
Requirement already satisfied: datasets>=2.5.2 in /usr/local/lib/python3.12/dist-packages (from be-great>=0.0.5->synthcity) (4.0.0)
Requirement already satisfied: transformers>=4.22.1 in /usr/local/lib/python3.12/dist-packages (from be-great>=0.0.5->synthcity) (4.57.1)
Requirement already satisfied: accelerate>=0.20.1 in /usr/local/lib/python3.12/dist-packages (from be-great>=0.0.5->synthcity) (1.11.0)
Requirement already satisfied: pytorch-lightning>=2.4 in /usr/local/lib/python3.12/dist-packages (from decaf-synthetic-data>=0.1.6->synthcity) (2.5.6)
Requirement already satisfied: torchtext>=0.10 in /usr/local/lib/python3.12/dist-packages (from decaf-synthetic-data>=0.1.6->synthcity) (0.17.2)
Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (from fastai<2.8->synthcity) (24.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from fastai<2.8->synthcity) (25.0)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from fastai<2.8->synthcity) (0.0.7)
Requirement already satisfied: torchvision>=0.11 in /usr/local/lib/python3.12/dist-packages (from fastai<2.8->synthcity) (0.17.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from fastai<2.8->synthcity) (3.10.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from fastai<2.8->synthcity) (2.32.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from fastai<2.8->synthcity) (6.0.3)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.12/dist-packages (from fastai<2.8->synthcity) (1.0.3)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from fastai<2.8->synthcity) (11.3.0)
Requirement already satisfied: spacy<4 in /usr/local/lib/python3.12/dist-packages (from fastai<2.8->synthcity) (3.8.8)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.12/dist-packages (from lifelines<0.30.0,>=0.29.0->synthcity) (1.8.0)
Requirement already satisfied: autograd-gamma>=0.3 in /usr/local/lib/python3.12/dist-packages (from lifelines<0.30.0,>=0.29.0->synthcity) (0.5.0)
Requirement already satisfied: formulaic>=0.2.2 in /usr/local/lib/python3.12/dist-packages (from lifelines<0.30.0,>=0.29.0->synthcity) (1.2.1)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.12/dist-packages (from nflows>=0.14->synthcity) (2.19.0)
Requirement already satisfied: opt-einsum>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from opacus>=1.3->synthcity) (3.4.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna>=3.1->synthcity) (1.17.1)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna>=3.1->synthcity) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna>=3.1->synthcity) (2.0.44)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1->synthcity) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1->synthcity) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1->synthcity) (2025.2)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from pgmpy<1.0->synthcity) (3.2.5)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from pgmpy<1.0->synthcity) (0.14.5)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from pgmpy<1.0->synthcity) (1.5.2)
Requirement already satisfied: google-generativeai in /usr/local/lib/python3.12/dist-packages (from pgmpy<1.0->synthcity) (0.8.5)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->synthcity) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->synthcity) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->synthcity) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->synthcity) (0.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2->synthcity) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (3.20.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (1.13.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch<2.3,>=2.1->synthcity) (12.1.105)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch<2.3,>=2.1->synthcity) (12.6.85)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata->synthcity) (3.23.0)
Requirement already satisfied: torchtuples>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from pycox->synthcity) (0.2.2)
Requirement already satisfied: feather-format>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pycox->synthcity) (0.4.1)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.12/dist-packages (from pycox->synthcity) (3.15.1)
Requirement already satisfied: numba>=0.44 in /usr/local/lib/python3.12/dist-packages (from pycox->synthcity) (0.60.0)
Requirement already satisfied: py7zr>=0.11.3 in /usr/local/lib/python3.12/dist-packages (from pycox->synthcity) (1.0.0)
Requirement already satisfied: pybind11 in /usr/local/lib/python3.12/dist-packages (from pykeops->synthcity) (3.0.1)
Requirement already satisfied: keopscore==2.3 in /usr/local/lib/python3.12/dist-packages (from pykeops->synthcity) (2.3)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap->synthcity) (0.0.8)
Requirement already satisfied: pyts>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from tsai->synthcity) (0.13.0)
Requirement already satisfied: imbalanced-learn>=0.12.4 in /usr/local/lib/python3.12/dist-packages (from tsai->synthcity) (0.14.0)
Requirement already satisfied: psutil>=6.1.0 in /usr/local/lib/python3.12/dist-packages (from tsai->synthcity) (7.1.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.20.1->be-great>=0.0.5->synthcity) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.20.1->be-great>=0.0.5->synthcity) (0.6.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna>=3.1->synthcity) (1.3.10)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.5.2->be-great>=0.0.5->synthcity) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.5.2->be-great>=0.0.5->synthcity) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=2.5.2->be-great>=0.0.5->synthcity) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.5.2->be-great>=0.0.5->synthcity) (0.70.16)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines<0.30.0,>=0.29.0->synthcity) (1.3.0)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines<0.30.0,>=0.29.0->synthcity) (2.11.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines<0.30.0,>=0.29.0->synthcity) (2.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fastai<2.8->synthcity) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fastai<2.8->synthcity) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fastai<2.8->synthcity) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fastai<2.8->synthcity) (1.4.9)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.44->pycox->synthcity) (0.43.0)
Requirement already satisfied: texttable in /usr/local/lib/python3.12/dist-packages (from py7zr>=0.11.3->pycox->synthcity) (1.7.0)
Requirement already satisfied: pycryptodomex>=3.20.0 in /usr/local/lib/python3.12/dist-packages (from py7zr>=0.11.3->pycox->synthcity) (3.23.0)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from py7zr>=0.11.3->pycox->synthcity) (1.2.0)
Requirement already satisfied: pyzstd>=0.16.1 in /usr/local/lib/python3.12/dist-packages (from py7zr>=0.11.3->pycox->synthcity) (0.18.0)
Requirement already satisfied: pyppmd<1.3.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from py7zr>=0.11.3->pycox->synthcity) (1.2.0)
Requirement already satisfied: pybcj<1.1.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from py7zr>=0.11.3->pycox->synthcity) (1.0.6)
Requirement already satisfied: multivolumefile>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from py7zr>=0.11.3->pycox->synthcity) (0.2.3)
Requirement already satisfied: inflate64<1.1.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from py7zr>=0.11.3->pycox->synthcity) (1.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.1->synthcity) (1.17.0)
Requirement already satisfied: torchmetrics>0.7.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.4->decaf-synthetic-data>=0.1.6->synthcity) (1.8.2)
Requirement already satisfied: lightning-utilities>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.4->decaf-synthetic-data>=0.1.6->synthcity) (0.15.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->fastai<2.8->synthcity) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->fastai<2.8->synthcity) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->fastai<2.8->synthcity) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->fastai<2.8->synthcity) (2025.10.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (8.3.8)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (0.4.2)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (0.20.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy<4->fastai<2.8->synthcity) (75.2.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna>=3.1->synthcity) (3.2.4)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.22.1->be-great>=0.0.5->synthcity) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.22.1->be-great>=0.0.5->synthcity) (0.22.1)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.12/dist-packages (from google-generativeai->pgmpy<1.0->synthcity) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.12/dist-packages (from google-generativeai->pgmpy<1.0->synthcity) (2.28.1)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (from google-generativeai->pgmpy<1.0->synthcity) (2.187.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.12/dist-packages (from google-generativeai->pgmpy<1.0->synthcity) (2.38.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from google-generativeai->pgmpy<1.0->synthcity) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai->pgmpy<1.0->synthcity) (1.26.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<2.3,>=2.1->synthcity) (3.0.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pgmpy<1.0->synthcity) (1.0.2)

In [12]:
%pip install GReaT

Requirement already satisfied: GReaT in /usr/local/lib/python3.12/dist-packages (0.2.0)
Requirement already satisfied: Alchimia in /usr/local/lib/python3.12/dist-packages (from GReaT) (0.8.1)
Requirement already satisfied: alembic in /usr/local/lib/python3.12/dist-packages (from GReaT) (1.17.1)
Requirement already satisfied: appdirs in /usr/local/lib/python3.12/dist-packages (from GReaT) (1.4.4)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from GReaT) (25.4.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from GReaT) (8.3.0)
Requirement already satisfied: filesystems in /usr/local/lib/python3.12/dist-packages (from GReaT) (2024.8.1)
Requirement already satisfied: hyperlink in /usr/local/lib/python3.12/dist-packages (from GReaT) (21.0.0)
Requirement already satisfied: Minion in /usr/local/lib/python3.12/dist-packages (from GReaT) (0.24.0)
Requirement already satisfied: SQLAlchemy in /usr/local/lib/python3.12/dist-packages (from GReaT) (2.0.44)
Requirement already satisfied: toml in /usr/local/lib/python3.12/dist-packages (from GReaT) (0.10.2)
Requirement already satisfied: Twisted in /usr/local/lib/python3.12/dist-packages (from GReaT) (25.5.0)
Requirement already satisfied: txmusicbrainz in /usr/local/lib/python3.12/dist-packages (from GReaT) (0.1.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic->GReaT) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic->GReaT) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy->GReaT) (3.2.4)
Requirement already satisfied: pyrsistent in /usr/local/lib/python3.12/dist-packages (from filesystems->GReaT) (0.20.0)
Requirement already satisfied: zope-interface in /usr/local/lib/python3.12/dist-packages (from filesystems->GReaT) (8.1.1)
Requirement already satisfied: idna>=2.5 in /usr/local/lib/python3.12/dist-packages (from hyperlink->GReaT) (3.11)
Requirement already satisfied: cached-property in /usr/local/lib/python3.12/dist-packages (from Minion->GReaT) (2.0.1)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from Minion->GReaT) (1.0.0)
Requirement already satisfied: itsdangerous in /usr/local/lib/python3.12/dist-packages (from Minion->GReaT) (2.2.0)
Requirement already satisfied: Werkzeug in /usr/local/lib/python3.12/dist-packages (from Minion->GReaT) (3.1.3)
Requirement already satisfied: automat>=24.8.0 in /usr/local/lib/python3.12/dist-packages (from Twisted->GReaT) (25.4.16)
Requirement already satisfied: constantly>=15.1 in /usr/local/lib/python3.12/dist-packages (from Twisted->GReaT) (23.10.4)
Requirement already satisfied: incremental>=24.7.0 in /usr/local/lib/python3.12/dist-packages (from Twisted->GReaT) (24.7.2)
Requirement already satisfied: setuptools>=61.0 in /usr/local/lib/python3.12/dist-packages (from incremental>=24.7.0->Twisted->GReaT) (75.2.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic->GReaT) (3.0.3)

In [6]:
%pip install opacus==1.5.3

Collecting opacus==1.5.3
  Downloading opacus-1.5.3-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: numpy<2.0,>=1.15 in /usr/local/lib/python3.12/dist-packages (from opacus==1.5.3) (1.26.4)
Requirement already satisfied: torch>=2.0 in /usr/local/lib/python3.12/dist-packages (from opacus==1.5.3) (2.2.2)
Requirement already satisfied: scipy>=1.2 in /usr/local/lib/python3.12/dist-packages (from opacus==1.5.3) (1.16.3)
Requirement already satisfied: opt-einsum>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from opacus==1.5.3) (3.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (3.20.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (4.15.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (2.8.8)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->opacus==1.5.3) (12.1.105)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.0->opacus==1.5.3) (12.6.85)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0->opacus==1.5.3) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->torch>=2.0->opacus==1.5.3) (1.3.0)
Downloading opacus-1.5.3-py3-none-any.whl (251 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.7/251.7 kB 6.4 MB/s eta 0:00:00
Installing collected packages: opacus
  Attempting uninstall: opacus
    Found existing installation: opacus 1.5.4
    Uninstalling opacus-1.5.4:
      Successfully uninstalled opacus-1.5.4
Successfully installed opacus-1.5.3

In [2]:
from synthcity.plugins import Plugins

Plugins(categories=["generic", "privacy"]).list()

[KeOps] Warning : CUDA libraries not found or could not be loaded; Switching to CPU only.

[2025-11-16T11:57:22.850635+0000][15954][CRITICAL] load failed:
GReaT is not installed. Please install it with pip install GReaT.
Please be aware that GReaT is only available for python >= 3.9.

[2025-11-16T11:57:22.853192+0000][15954][CRITICAL] load failed: module 'synthcity.plugins.generic.plugin_great' has no attribute 'plugin'
[2025-11-16T11:57:22.854185+0000][15954][CRITICAL] module plugin_great load failed
[2025-11-16T11:57:22.859254+0000][15954][CRITICAL] Error importing TabularGoggle: No module named 'dgl'
[2025-11-16T11:57:22.864842+0000][15954][CRITICAL] module disabled: /usr/local/lib/python3.12/dist-packages/synthcity/plugins/generic/plugin_goggle.py

['uniform_sampler',
 'adsgan',
 'decaf',
 'rtvae',
 'bayesian_network',
 'dpgan',
 'privbayes',
 'nflow',
 'ddpm',
 'tvae',
 'marginal_distributions',
 'pategan',
 'aim',
 'arf',
 'dummy_sampler',
 'ctgan']

In [4]:
X["target"] = y
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1
299,68,1,4,144,193,1,0,141,0,3.4,2,2.0,7.0,2
300,57,1,4,130,131,0,0,115,1,1.2,2,1.0,7.0,3
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,3.0,1
302,38,1,3,138,175,0,0,173,0,0.0,1,NaN,3.0,0

In [5]:
plugin = Plugins().get("ctgan", n_iter = 100)

[2025-11-16T12:18:50.779499+0000][15954][CRITICAL] load failed: module 'synthcity.plugins.generic.plugin_great' has no attribute 'plugin'
[2025-11-16T12:18:50.779499+0000][15954][CRITICAL] load failed: module 'synthcity.plugins.generic.plugin_great' has no attribute 'plugin'
[2025-11-16T12:18:50.782772+0000][15954][CRITICAL] load failed: module 'synthcity.plugins.generic.plugin_great' has no attribute 'plugin'
[2025-11-16T12:18:50.782772+0000][15954][CRITICAL] load failed: module 'synthcity.plugins.generic.plugin_great' has no attribute 'plugin'
[2025-11-16T12:18:50.784312+0000][15954][CRITICAL] module plugin_great load failed
[2025-11-16T12:18:50.784312+0000][15954][CRITICAL] module plugin_great load failed
[2025-11-16T12:18:50.785694+0000][15954][CRITICAL] module disabled: /usr/local/lib/python3.12/dist-packages/synthcity/plugins/generic/plugin_goggle.py
[2025-11-16T12:18:50.785694+0000][15954][CRITICAL] module disabled: /usr/local/lib/python3.12/dist-packages/synthcity/plugins/generic/plugin_goggle.py

### CTGAN plugin in synthcity

Most parameters of the plugin describe architectures or training loop of Generator (G) and Discriminator (D) neural networks.

#### Generator parameters

- `generator_n_layers_hidden`: how many hidden layers the generator neural network has (excluding input/out). More layers -> more capacity, but slower + risk of overfitting.
- `generator_n_units_hidden`: number of neurons per hidden layer. Controls generator model size.
- `generator_nonlin`: activation function used between layers:
    - `leaky_relu` - default, stable for GANs
    - `relu` - simpler
    - `elu` / `selu` - sometimes help with continuous skewed data
- `generator_dropout`: fraction of neurons randomly dropped during training. Prevents overfitting. Usually 0 for tabular GANs.
- `n_iter`: total number of training iterations (epochs). Higher -> better model (until overfitting), longer training.

#### Discriminator parameters

- `discriminator_n_layers_hidden`: how many hidden layers the discriminator has.
- `discriminator_n_units_hidden`: number of neurons per layer
- `discriminator_nonlin`: activation function for the discriminator.
- `discriminator_dropout`: dropout regularization for the discriminator.
- `discriminator_n_inter`: number of discriminator update steps per cycle.

#### Optimization and training

- `lr`: learning rate for both generator and discriminator
- `weight_decay`: L2 regularization on weights, which prevents exploding weights (and overfitting). Adds penalty to the loss function proportional to the sum of squares of the model's weights.
- `batch_size`: mini-batch size used during training. For a small dataset like in our case (303 rows), values 32-128 work good.
- `random_state`: random seed for reproducibility.
- `clipping_value`: gradient clipping threshold.

#### Preprocessing / encoding

- `encoder_max_clusters`: continuous variables are encoded using mode-specific normalization. This parameter controls the max number of mixture components (clusters) used. More clusters = better modeling of multimodal distributions, slower training.

In [7]:
plugin.fit(X)

100%|██████████| 100/100 [00:19<00:00,  5.09it/s]

In [8]:
plugin.generate(50)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,58,0,4,155,331,0,0,167,0,1.579432,1,2.0,3.0,0
1,59,0,3,150,314,0,2,165,0,1.523318,1,3.0,3.0,0
2,62,0,4,174,362,0,2,164,0,0.389325,2,2.0,3.0,1
3,61,0,3,154,329,0,2,164,0,1.585375,1,1.0,3.0,0
4,63,0,1,151,368,0,0,174,0,0.244118,2,2.0,3.0,1
5,59,1,1,185,321,0,2,178,0,0.177883,1,2.0,3.0,2
6,58,0,3,173,356,0,0,171,0,1.403261,2,2.0,3.0,0
7,59,0,4,160,382,0,0,172,0,1.766934,1,2.0,3.0,0
8,63,0,3,155,336,0,0,172,0,0.217632,1,0.0,3.0,0
9,56,0,3,148,318,0,0,163,0,0.302441,1,0.0,3.0,0
10,59,0,3,176,325,1,0,170,0,1.986485,1,2.0,3.0,0
11,62,0,2,169,334,0,0,156,0,0.203944,2,1.0,3.0,0
12,58,0,2,150,227,0,2,158,0,0.134254,2,2.0,3.0,0
13,60,0,1,173,338,0,0,178,0,0.257731,2,0.0,3.0,0
14,61,0,4,145,347,0,0,143,0,1.897627,2,2.0,3.0,2
15,65,1,1,153,303,1,2,165,0,1.357658,1,1.0,3.0,2
16,65,0,4,161,367,0,2,163,0,1.326520,2,2.0,3.0,2
17,48,0,4,167,347,0,2,155,0,1.532475,2,2.0,3.0,3
18,62,0,3,178,402,0,2,168,0,0.245078,1,2.0,3.0,0
19,58,0,1,135,318,1,2,171,0,0.170144,2,3.0,3.0,0
20,61,0,3,141,330,0,2,130,1,1.536813,2,3.0,3.0,2
21,63,1,3,186,365,0,0,171,0,1.436497,2,0.0,3.0,2
22,60,0,4,141,364,0,0,153,0,1.606124,2,2.0,7.0,1
23,63,0,3,161,336,0,0,164,0,1.622740,1,1.0,3.0,0
24,62,0,4,169,357,0,2,155,0,2.023565,2,2.0,3.0,1
25,55,0,3,168,342,0,2,161,0,1.367135,1,1.0,3.0,1
26,62,0,2,154,334,0,0,172,0,2.176316,1,0.0,3.0,0
27,61,0,3,158,345,0,2,147,0,1.681699,2,2.0,3.0,0
28,61,0,4,170,363,0,0,168,0,1.461263,2,NaN,3.0,0
29,56,0,4,143,328,0,2,170,0,1.854986,1,0.0,3.0,1
30,63,1,4,158,373,0,2,159,1,1.754129,2,2.0,7.0,1
31,59,0,3,165,288,0,2,160,0,1.717019,2,1.0,3.0,0
32,60,0,1,164,351,0,0,181,0,1.836137,2,1.0,3.0,0
33,61,0,4,153,353,0,2,114,1,1.941608,2,2.0,7.0,1
34,65,0,3,156,346,0,2,172,0,1.872616,1,2.0,3.0,0
35,68,1,4,149,363,0,2,158,0,2.031606,2,2.0,7.0,1
36,60,0,4,161,344,0,2,159,1,1.737794,2,2.0,6.0,0
37,62,0,3,150,331,0,2,166,0,3.568297,2,3.0,3.0,0
38,59,0,4,163,368,0,2,170,0,0.236346,2,2.0,3.0,0
39,60,0,1,179,336,0,0,169,0,0.267138,1,2.0,3.0,0
40,61,0,4,152,384,0,0,164,0,0.146713,1,2.0,3.0,0
41,64,0,4,157,301,0,2,149,0,1.748280,1,0.0,3.0,2
42,63,1,1,181,365,0,0,172,0,1.433535,2,1.0,3.0,0
43,57,0,3,174,359,0,0,178,0,1.637598,1,2.0,3.0,0
44,60,0,3,161,329,0,2,177,0,0.251197,1,1.0,3.0,0
45,62,0,2,174,373,0,0,175,0,1.673054,1,0.0,3.0,0
46,64,0,4,160,379,0,0,170,1,1.715156,2,2.0,3.0,1
47,62,1,4,135,342,0,0,117,1,2.016534,2,0.0,3.0,2
48,61,0,1,157,359,0,0,165,0,0.239221,1,1.0,3.0,0
49,57,0,3,141,286,0,0,162,0,1.890523,1,2.0,3.0,0